-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 00:27:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema matriculaSanJose
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `matriculaSanJose` ;

-- -----------------------------------------------------
-- Schema matriculaSanJose
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matriculaSanJose` ;
USE `matriculaSanJose` ;

-- -----------------------------------------------------
-- Table `matriculaSanJose`.`ACTIVIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`ACTIVIDAD` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`ACTIVIDAD` (
  `COD_ACTIVIDAD` INT NOT NULL,
  `NOMBRE_ACTIVIDAD` VARCHAR(45) NOT NULL,
  `HORARIO_ACTIVIDAD` VARCHAR(45) NULL,
  `CUPO_MAXIMO` INT NULL,
  `TIPO ACTIVIDAD_COD_TIPO` INT NOT NULL,
  PRIMARY KEY (`COD_ACTIVIDAD`),
  UNIQUE INDEX `COD_ACTIVIDAD_UNIQUE` (`COD_ACTIVIDAD` ASC) VISIBLE,
  INDEX `fk_ACTIVIDAD_TIPO ACTIVIDAD1_idx` (`TIPO ACTIVIDAD_COD_TIPO` ASC) VISIBLE,
  CONSTRAINT `fk_ACTIVIDAD_TIPO ACTIVIDAD1`
    FOREIGN KEY (`TIPO ACTIVIDAD_COD_TIPO`)
    REFERENCES `matriculaSanJose`.`TIPO ACTIVIDAD` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`MATRICULA` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`MATRICULA` (
  `COD_MATRICULA` VARCHAR(45) NOT NULL,
  `USUARIO_COD_USER` INT NOT NULL,
  `ACTIVIDAD_COD` INT NOT NULL,
  `FECHA` DATE NULL,
  PRIMARY KEY (`COD_MATRICULA`),
  INDEX `fk_USUARIO_has_ACTIVIDAD_ACTIVIDAD1_idx` (`ACTIVIDAD_COD` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_ACTIVIDAD_USUARIO1_idx` (`USUARIO_COD_USER` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_ACTIVIDAD_USUARIO1`
    FOREIGN KEY (`USUARIO_COD_USER`)
    REFERENCES `matriculaSanJose`.`USUARIO` (`COD_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_ACTIVIDAD_ACTIVIDAD1`
    FOREIGN KEY (`ACTIVIDAD_COD`)
    REFERENCES `matriculaSanJose`.`ACTIVIDAD` (`COD_ACTIVIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`MENU` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`MENU` (
  `COD_MENU` INT NOT NULL,
  `OPCION` VARCHAR(45) NULL,
  `URL` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_MENU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`PERMISOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`PERMISOS` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`PERMISOS` (
  `ROL_COD_TIPO` INT NOT NULL,
  `MENU_COD_MENU` INT NOT NULL,
  `CRUD` VARCHAR(45) NULL,
  PRIMARY KEY (`ROL_COD_TIPO`, `MENU_COD_MENU`),
  INDEX `fk_ROL_has_MENU_MENU1_idx` (`MENU_COD_MENU` ASC) VISIBLE,
  INDEX `fk_ROL_has_MENU_ROL1_idx` (`ROL_COD_TIPO` ASC) VISIBLE,
  CONSTRAINT `fk_ROL_has_MENU_ROL1`
    FOREIGN KEY (`ROL_COD_TIPO`)
    REFERENCES `matriculaSanJose`.`ROL` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROL_has_MENU_MENU1`
    FOREIGN KEY (`MENU_COD_MENU`)
    REFERENCES `matriculaSanJose`.`MENU` (`COD_MENU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`ROL` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`ROL` (
  `COD_TIPO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE TIPO` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO`),
  UNIQUE INDEX `COD_TIPOUSER_UNIQUE` (`COD_TIPO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`TIPO ACTIVIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`TIPO ACTIVIDAD` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`TIPO ACTIVIDAD` (
  `COD_TIPO` INT NOT NULL,
  `NOMBRE_ACTIVIDAD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_TIPO`),
  UNIQUE INDEX `COD_TIPO_UNIQUE` (`COD_TIPO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`USUARIO` (
  `COD_USER` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_NAC` DATETIME NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_USER`),
  UNIQUE INDEX `COD_USER_UNIQUE` (`COD_USER` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculaSanJose`.`USUARIO_ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculaSanJose`.`USUARIO_ROL` ;

CREATE TABLE IF NOT EXISTS `matriculaSanJose`.`USUARIO_ROL` (
  `USUARIO_COD_USER` INT NOT NULL,
  `ROL_COD_TIPO` INT NOT NULL,
  PRIMARY KEY (`USUARIO_COD_USER`, `ROL_COD_TIPO`),
  INDEX `fk_USUARIO_has_ROL_ROL1_idx` (`ROL_COD_TIPO` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_ROL_USUARIO1_idx` (`USUARIO_COD_USER` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_ROL_USUARIO1`
    FOREIGN KEY (`USUARIO_COD_USER`)
    REFERENCES `matriculaSanJose`.`USUARIO` (`COD_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_ROL_ROL1`
    FOREIGN KEY (`ROL_COD_TIPO`)
    REFERENCES `matriculaSanJose`.`ROL` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
